name: Tests

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [waf]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false

      - name: Download dependencies
        working-directory: ${{ matrix.service }}
        run: go mod download

      - name: Verify dependencies
        working-directory: ${{ matrix.service }}
        run: go mod verify

      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: go test -v ./...